### ISSUE TITLE
Parser bugs and project status

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [FallenAngel97/tree-sitter-rego#1]
Hello

I've tried to use this project from NeoVim's treesitter plugin, but it seems that valid OPA are parsed incorrectly, I can see ERRORs in Treesitter playground.

Is this project alive ? Can I post bug reports with rego errors ?

**Comment by FallenAngel97** [comment]
Hi, there are and will be errors, because I work on it part-time. If you want to you can create a merge request, which I can review. 
I am populating this repo as I need, so in case of new functionality - it's up to the community to extend this project/fork
